//This file contains functions that deal with files.

FUNCTION AQCUIRE{
  PARAMETER FILENAME.
  //CHECK FOR CONNECTION
  //ACQUIRE FILE.
  //POSSIBLY SHOULD ACQUIRE ALL FILES AT LAUNCH.
  PRINT FILENAME + " HAS BEEN AQCUIRED.".
}
