CLEARSCREEN.

PRINT SHIP:GEOPOSITION.
PRINT SHIP:ORBIT:ARGUMENTOFPERIAPSIS.


IF SHIP:STATUS = "PRELAUNCH"{
  RUN LAUNCH(80000).
}

AG1 ON.

MONITORFORMANOEUVRES(10000).

SET B TO 3.
PRINT "PRINTING LONGITUDE OF ASCENDING NODE.".
PRINT SHIP:ORBIT:LONGITUDEOFASCENDINGNODE.
PRINT "PRINTING ARGUMENT OF PERIAPSIS.".
PRINT SHIP:ORBIT:ARGUMENTOFPERIAPSIS.


UNTIL B = 4{

  PRINT SHIP:GEOPOSITION.
  WAIT 60.
}
