
CLEARSCREEN.
print "TESTING SUICIDE SCRIPT".
SET Y0 TO ALT:RADAR.
PRINT Y0.

LOCK STEERING TO HEADING(90, 90).

SET THROT TO 0.6.
LOCK THROTTLE TO THROT.
WAIT 1.
STAGE.

wait until ship:altitude > 250.
set THROT to 0.2.
WAIT UNTIL SHIP:ALTITUDE > 500.

SET THROT TO 0.
GEAR ON.

WAIT UNTIL SHIP:VERTICALSPEED < 0.
WAIT 0.1.
PRINT "FINDING K2".
SET K2 TO 0.5*SHIP:MASS*SHIP:VERTICALSPEED*SHIP:VERTICALSPEED.
SET Y2 TO ALT:RADAR.
SET G2 TO SHIP:MASS*9.81*Y2.
SET Y1 TO (K2 + G2)/(SHIP:MAXTHRUST).
PRINT "Y1: ".
PRINT Y1.

WAIT UNTIL ALT:RADAR <= (Y1).
PRINT "BURNING".
SET THROT TO 1.
WAIT UNTIL SHIP:VERTICALSPEED >= -5.
set throt to (ship:mass*9.81/ship:maxthrust).
wait until alt:radar <= (Y0 + 0.1).
SET THROT TO 0.
wait 1.
lock throttle to 0.
wait 5.
