//HOVERSCRIPT
SET KP TO 0.01.
SET KI TO 0.0005.
SET KD TO 0.005.

FUNCTION PIDLOOP{
  PARAMETER TARGETALT.
  PARAMETER CURRENTALT.
  PARAMETER KP.
  PARAMETER KI.
  PARAMETER KD.

  SET DELTA TO TARGETALT - CURRENTALT.

  SET OUTPUT TO 0.
  SET NOW TO TIME:SECONDS.

  SET P TO DELTA.
  SET I TO 0.
  SET D TO 0.

  IF LASTTIME > 0{
    SET I TO TOTALP + ((P + LASTP)/2 * (NOW- LASTTIME)).
    SET D TO (P - LASTP)/(NOW - LASTTIME).
  }

  SET OUTPUT TO KP * P + KI * I + KD * D.

  SET LASTP TO P.
  SET LASTTIME TO NOW.
  SET TOTALP TO I.

  LOG CURRENTALT TO LOG1.txt.

  RETURN OUTPUT.
}

CLEARSCREEN.
print "TESTING HOVER SCRIPT".


LOCK STEERING TO HEADING(90, 90).


SET THROT TO 0.3.
LOCK THROTTLE TO THROT.
WAIT 1.
STAGE.

WAIT UNTIL SHIP:ALTITUDE > 500.

set TARGETALT to 500.

SET LASTP TO 0.
SET LASTTIME TO 0.
SET TOTALP TO 0.

UNTIL STAGE:LIQUIDFUEL < 10{
  SET THROT TO MAX(0, MIN(PIDLOOP(500, ALTITUDE, KP, KI, KD), 1)).
  WAIT 0.001.
}

SET THROT TO 0.

chutes on.
